[package]
name = "romanize-jp"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
lindera = { version = "0.43.0", features = ["ipadic"] }
serde = "1.0.219"
serde_json = "1.0.140"
tokio = { version = "1.45.1", features = ["full"] }
tracing-subscriber = "0.3.19"
wana_kana = "4.0.0"
